services:
  - type: web
    name: cyber-attack-storyteller
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 600 backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
